### ISSUE TITLE
Refine row data using the `links.json` metadata in each bundle

### ISSUE THREAD

**Issue by GPelayo** [HumanCellAtlas/hca_bundles_to_csv#11]
Currently, the script generates a CSV or TSV where the each row represents a specific file from a specific bundle. However, some rows contain data that is not linked to the file that row represents. The script assumes a file is related or linked to all the metadata in that file's bundle. The `links.json` file contains info on the links between the metadata and files and isn't used in this script. By utilizing `links.json`, the data in each row will only pertain to the file it represents.

**Comment by simonjupp** [comment]
Can you give me an example?

**Comment by hannes-ucsc** [comment]
Moved to https://github.com/DataBiosphere/azul/issues/1229
