### ISSUE TITLE
Add `file_uuid` and `file_version` columns to metadata tsv 

### ISSUE THREAD

**Issue by simonjupp** [HumanCellAtlas/hca_bundles_to_csv#12]
The tsv only contains the uuid of the metadata document about the file, but doesn't contain the DSS uuid or version uuid of the actual file. This can only be retrieved from the bundle manifest by looking up on the file name

**Comment by theathorn** [comment]
@jahilton  automation is not required for General Availability. Removing from epic.

**Comment by hannes-ucsc** [comment]
I checked that these are present in the full manifests on prod.

![Uploading Screen Shot 2019-08-19 at 12.21.26 PM.png…]()

**Comment by hannes-ucsc** [comment]
The equivalent functionality was added to Azul in https://github.com/DataBiosphere/azul/issues/1068 for the the automatted generation of the full manifest.
