### ISSUE TITLE
Prepend `*.file_core.` to file_name and file_format columns

### ISSUE THREAD

**Issue by GPelayo** [HumanCellAtlas/hca_bundles_to_csv#7]
Is there a reason `file_name` and `file_format` columns don't include `file_core.` in their names? @simonjupp

**Comment by simonjupp** [comment]
Ideally this would be fully qualified like all the other headers e.g sequence_file.file_core.file_name.  But we typically have a mixture of file types so we can’t pick just one. 

Couple of options
1. Keep it as it is for now, file_name is the key and a special reserved header name. Also happy to prefix with file_core if you want. We could even use *.file_core.file_name so it kind of matches with the other headers and implies a mixture of types.   
2. Introduce a new column for each type. I tried this before and it was very ugly
3. Ask users to specify the file type they want metadata for when downloading the TSV, with sequence_file being the default

**Comment by hannes-ucsc** [comment]
`*.file_core.file_name` seems to be the best option to me.
